### PR TITLE
home screen document

### PR DESCRIPTION
**Pull request by drucelweisse**
Added home screen of OneTwoTrip mobile application.

### CODE REVIEW

**Comment by drucelweisse** [comment]
@akaDuality for some reason i can't add you as reviewer 🤔

**Comment by akaDuality** [comment]
@drucelweisse It probably happens because you are not mantainer at this repository or because PR is from fork, don't now exactly.

Can you add some different text to stories section? It could look like broken part of VoiceOver

**Comment by akaDuality** [comment]
I'll fix conflict by automated tool, don't worry about `structure.json` updating (better to remove your changes of it from the PR)

**Comment by drucelweisse** [comment]
updated document with different stories

**Review by akaDuality — APPROVED** [review]

**Comment by akaDuality** [comment]
Screenshot 2023-02-04 at 22 56 37

For release we should prepare at least 3-5 samples for each project to make it beautiful. We had at least one week for that

**Pull request merged**
